feat(BBD-825): create cart
groupby/storefront-core pull request #165
Opened 2018-01-22 20:28 UTC by treeforever

2018-02-02 16:39 UTC, Vic-Dev requested changes
Small things :) It's been a 🌲-t working with you!

2018-02-02 16:39 UTC, Vic-Dev commented on src/core/index.ts
>  import ProductTransformer from './product-transformer';
do `import ProductTransformer, { TransformUtils } from './product-transformer';`

2018-02-02 16:39 UTC, Vic-Dev commented on src/core/index.ts
> +import { TransformUtils } from './product-transformer'
Remove

2018-02-02 16:39 UTC, Vic-Dev commented on src/services/cart.ts
> +    // this.app.flux.on(Events.ADD_TO_CART, this.addToCart);
Don't forget to do this!

2019-01-30 18:52 UTC, jmbtutor commented
Archiving repo. Closing.

2019-01-30 18:52 UTC, closed without merging